language: go

sudo: true

go:
  - 1.6

install:
  - true

services:
  - mysql

before_script:
  # dependency
  - make depend
  - gometalinter -i
  # upgrade mysql to 5.7
  - bash travis.upgrade.mysql.sh

script:
  - gometalinter --concurrency=8 --vendor --disable-all --enable=golint --enable=gocyclo --enable=vetshadow --enable=deadcode --enable=goconst --enable=gosimple --enable=staticcheck --enable=deadcode --enable=dupl --linter='dupl:dupl -plumbing -threshold {duplthreshold} ./*.go | grep -v "_test.go"::(?P<path>[^\s][^:]+?\.go):(?P<line>\d+)-\d+:\s*(?P<message>.*)' ./...
  - bash test.sh

after_script:
  # cleanup
  - mysql -uroot -e 'drop database if exists solebtc_test;'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: freeusd:jaRsOvGWpjt9LPpJ0I4PqNwa
