language: go

sudo: true

go:
  - 1.6

install:
  - true

services:
  - mysql

before_script:
  # dependency
  - make depend
  - gometalinter -i
  # upgrade mysql to 5.7
  - bash travis.upgrade.mysql.sh

script:
  - gometalinter --deadline=60s --disable-all --vendor --concurrency=8 --enable=goimports --enable=golint --enable=vetshadow --enable=goconst --enable=gosimple --enable=staticcheck --enable=dupl --enable=gocyclo --linter='dupl:dupl -plumbing -threshold {duplthreshold} ./*.go | grep -v "_test.go"::(?P<path>[^\s][^:]+?\.go):(?P<line>\d+)-\d+:\s*(?P<message>.*)' --linter='gocyclo:gocyclo -over {10} ./*.go | grep -v "*/handlers/v1/offerwall.go"::(?P<cyclo>\d+)\s+\S+\s(?P<function>\S+)\s+(?P<path>[^:]+):(?P<line>\d+):(\d+)' ./...
  - bash test.sh

after_script:
  # cleanup
  - mysql -uroot -e 'drop database if exists sole_test;'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: solefaucet:jaRsOvGWpjt9LPpJ0I4PqNwa
