language: go

sudo: false

go:
  - 1.5.3

install:
  # Add Godeps dependencies to GOPATH and PATH
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

before_script:
  - make depend

script:
  - gometalinter --install --update
  - gometalinter --disable=gotype --disable=errcheck --disable=deadcode --enable=goimports --deadline=60s ./...
  - bash test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: freeusd:jaRsOvGWpjt9LPpJ0I4PqNwa
